language: node_js
node_js:
  - "10"

stages:
  - test
  - build
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: build
      script:
        - npm run build
    - stage: release
      node_js: lts/*
      script:
        - npm run build && npx semantic-release
