version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    default_reviewers:
      - "jimcullenaus"
      - "lauraducky"
      - "arthurs"
      - "evangelinexx"
      - "drewfreyling"
      - "gillianmilne"
      - "chromadream"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
